# See https://pre-commit.com for more information
# See https://pre-commit.com/hooks.html for more hooks
repos:
-   repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.4.0
    hooks:
    -   id: trailing-whitespace
    -   id: end-of-file-fixer
    -   id: check-yaml
    -   id: check-added-large-files
    -   id: check-merge-conflict
    -   id: mixed-line-ending
        args: ['--fix=lf']
    -   id: check-case-conflict

# Python specific hooks
-   repo: https://github.com/pycqa/isort
    rev: 5.12.0
    hooks:
    -   id: isort
        args: ["--profile", "black"]

-   repo: https://github.com/psf/black
    rev: 23.3.0
    hooks:
    -   id: black

-   repo: https://github.com/pycqa/flake8
    rev: 6.0.0
    hooks:
    -   id: flake8
        additional_dependencies: [flake8-docstrings]

# JavaScript/TypeScript specific hooks
-   repo: https://github.com/pre-commit/mirrors-eslint
    rev: v8.38.0
    hooks:
    -   id: eslint
        files: \.(js|ts|jsx|tsx)$
        types: [file]
        additional_dependencies:
        -   eslint@8.38.0
        -   eslint-config-prettier@8.8.0
        -   eslint-plugin-prettier@4.2.1
        -   prettier@2.8.7

-   repo: https://github.com/pre-commit/mirrors-prettier
    rev: v3.0.0-alpha.9-for-vscode
    hooks:
    -   id: prettier
        types_or: [javascript, jsx, ts, tsx, json, css, scss, yaml]
